#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("School.Droid.Resource", IsApplication=true)]

namespace School.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int MenuArray = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int actionBarBackgroundColor = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int actionBarTextColor = 2131099649;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_other = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int action_search = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int drawer_shadow_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int drawer_shadow_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int EditText = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_drawer_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_drawer_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int monoandroidsplash = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int SguIcon = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08003a
			public const int btDangNhap = 2131230778;
			
			// aapt resource value: 0x7f080042
			public const int content_frame = 2131230786;
			
			// aapt resource value: 0x7f080041
			public const int drawer_layout = 2131230785;
			
			// aapt resource value: 0x7f080043
			public const int left_drawer = 2131230787;
			
			// aapt resource value: 0x7f080036
			public const int linear1 = 2131230774;
			
			// aapt resource value: 0x7f080011
			public const int linear10 = 2131230737;
			
			// aapt resource value: 0x7f080001
			public const int linear11 = 2131230721;
			
			// aapt resource value: 0x7f08003b
			public const int linear2 = 2131230779;
			
			// aapt resource value: 0x7f080009
			public const int linear45 = 2131230729;
			
			// aapt resource value: 0x7f080018
			public const int linear6 = 2131230744;
			
			// aapt resource value: 0x7f08000f
			public const int linearHP = 2131230735;
			
			// aapt resource value: 0x7f08001e
			public const int linearLH = 2131230750;
			
			// aapt resource value: 0x7f080033
			public const int linearThu = 2131230771;
			
			// aapt resource value: 0x7f080025
			public const int linearTiet = 2131230757;
			
			// aapt resource value: 0x7f08003d
			public const int linearTime = 2131230781;
			
			// aapt resource value: 0x7f080002
			public const int listDT = 2131230722;
			
			// aapt resource value: 0x7f080012
			public const int listHP = 2131230738;
			
			// aapt resource value: 0x7f080024
			public const int listLH = 2131230756;
			
			// aapt resource value: 0x7f080034
			public const int listLHTuan = 2131230772;
			
			// aapt resource value: 0x7f080037
			public const int listLT = 2131230775;
			
			// aapt resource value: 0x7f080026
			public const int textView1 = 2131230758;
			
			// aapt resource value: 0x7f08002e
			public const int textView10 = 2131230766;
			
			// aapt resource value: 0x7f08002f
			public const int textView12 = 2131230767;
			
			// aapt resource value: 0x7f080030
			public const int textView13 = 2131230768;
			
			// aapt resource value: 0x7f080031
			public const int textView14 = 2131230769;
			
			// aapt resource value: 0x7f080032
			public const int textView15 = 2131230770;
			
			// aapt resource value: 0x7f080027
			public const int textView2 = 2131230759;
			
			// aapt resource value: 0x7f080028
			public const int textView3 = 2131230760;
			
			// aapt resource value: 0x7f080029
			public const int textView4 = 2131230761;
			
			// aapt resource value: 0x7f08002a
			public const int textView5 = 2131230762;
			
			// aapt resource value: 0x7f08002b
			public const int textView7 = 2131230763;
			
			// aapt resource value: 0x7f08002c
			public const int textView8 = 2131230764;
			
			// aapt resource value: 0x7f08002d
			public const int textView9 = 2131230765;
			
			// aapt resource value: 0x7f08000c
			public const int txtDKT = 2131230732;
			
			// aapt resource value: 0x7f080007
			public const int txtDRL = 2131230727;
			
			// aapt resource value: 0x7f08000d
			public const int txtDT = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int txtDTK = 2131230734;
			
			// aapt resource value: 0x7f08003f
			public const int txtGioBD = 2131230783;
			
			// aapt resource value: 0x7f080008
			public const int txtHeaderDT = 2131230728;
			
			// aapt resource value: 0x7f080035
			public const int txtHocKy = 2131230773;
			
			// aapt resource value: 0x7f080000
			public const int txtHocKyDT = 2131230720;
			
			// aapt resource value: 0x7f080010
			public const int txtHocKyHP = 2131230736;
			
			// aapt resource value: 0x7f08001d
			public const int txtHocKyLH = 2131230749;
			
			// aapt resource value: 0x7f08001a
			public const int txtHocPhi = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int txtMienGiam = 2131230747;
			
			// aapt resource value: 0x7f08003c
			public const int txtMonHoc = 2131230780;
			
			// aapt resource value: 0x7f08000a
			public const int txtMonHocDT = 2131230730;
			
			// aapt resource value: 0x7f080019
			public const int txtMonHocHP = 2131230745;
			
			// aapt resource value: 0x7f08001f
			public const int txtMonHoc_HK = 2131230751;
			
			// aapt resource value: 0x7f08001c
			public const int txtPhaiDong = 2131230748;
			
			// aapt resource value: 0x7f080040
			public const int txtPhongThi = 2131230784;
			
			// aapt resource value: 0x7f080023
			public const int txtPhong_HK = 2131230755;
			
			// aapt resource value: 0x7f080022
			public const int txtSoTiet_HK = 2131230754;
			
			// aapt resource value: 0x7f080003
			public const int txtTB10 = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int txtTB4 = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int txtTBTL10 = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int txtTBTL4 = 2131230726;
			
			// aapt resource value: 0x7f080017
			public const int txtTCN = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int txtTDD = 2131230742;
			
			// aapt resource value: 0x7f080013
			public const int txtTSTC = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int txtTSTHP = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int txtTTLD = 2131230741;
			
			// aapt resource value: 0x7f08003e
			public const int txtThoiGian = 2131230782;
			
			// aapt resource value: 0x7f080020
			public const int txtThu_HK = 2131230752;
			
			// aapt resource value: 0x7f08000b
			public const int txtTiLe = 2131230731;
			
			// aapt resource value: 0x7f080021
			public const int txtTietBD_HK = 2131230753;
			
			// aapt resource value: 0x7f080039
			public const int txtmk = 2131230777;
			
			// aapt resource value: 0x7f080038
			public const int txtmsv = 2131230776;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DiemThi = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int drawer_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DTFooter = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DTHeader = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DTRow = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int HocPhi = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int HocPhiHeader = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int HocPhiRow = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int LHTuanHeader = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int LHTuanRow = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int LichHoc = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int LichHocHeader = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int LichHocRow = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int LichThi = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int LogIn = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int LTHeader = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int LTRow = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Main = 2130903057;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int DrawerClose = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int DrawerOpen = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int action_websearch = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070005
			public const int Mono_Android_Theme_Splash = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int MyTheme = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int MyTheme_ActionBar_TitleTextStyle = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int MyTheme_ActionBarStyle = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int Row = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int RowHeader = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
